### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by MasterPuffin** [Cloud-RF/tak-server#34]
When running the script after the certificate creation I get the following error

  ```
java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.bbn.marti.takcl.cli.CommandCommon.invokeMethodFromModuleWithParams(CommandCommon.java:85)
        at com.bbn.marti.takcl.cli.advanced.AdvancedParamParser.execute(AdvancedParamParser.java:279)
        at com.bbn.marti.takcl.cli.advanced.AdvancedCliMainHelper.main(AdvancedCliMainHelper.java:127)
        at com.bbn.marti.UserManager.main(UserManager.java:58)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.bbn.marti.takcl.cli.CommandCommon.invokeMethodFromModuleWithParams(CommandCommon.java:52)
        ... 3 more
Caused by: class org.apache.ignite.IgniteException: Failed to find deployed service: distributed-user-file-manager
        at org.apache.ignite.internal.processors.service.GridServiceProxy.invokeMethod(GridServiceProxy.java:201)
        at org.apache.ignite.internal.processors.service.GridServiceProxy$ProxyInvocationHandler.invoke(GridServiceProxy.java:498)
        at com.sun.proxy.$Proxy43.getUsers(Unknown Source)
        at com.bbn.marti.takcl.AppModules.OnlineFileAuthModule.innerUserCertMod(OnlineFileAuthModule.java:137)
        at com.bbn.marti.takcl.AppModules.OnlineFileAuthModule.usermod(OnlineFileAuthModule.java:91)
        ... 8 more
java.lang.reflect.InvocationTargetException
  ```
-->

# Environment

Please provide as much information as possible about your environment:

Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3
On Ubuntu 22.04 
1 vCPU
2GB
on DigitalOcean Droplet

**Comment by AlexWinder** [comment]
This doesn't look to be an issue with the Docker environment, given that the messages you are seeing are Java errors which are outside of the scope of this repository.

That said, your system environment has resources well below the requirements required as suggested in the official guidance. Try reinstalling on a machine with the suggested minimum requirements - https://tak.gov/products/tak-server.

![image](https://github.com/Cloud-RF/tak-server/assets/24867605/b2998fd3-a6c8-42ae-b320-481824cad2ab)

I'm closing this issue off as it does not appear to be an issue related to the repository. Feel free to reopen if you find reason to suggest otherwise.
