### ISSUE TITLE
Tak server not onnecting with my database

### ISSUE THREAD

**Issue by cugalord** [Cloud-RF/tak-server#35]
When installing the TAK server on digital ocean droplet i get this error both with 4.8 and 4.9 version, tried multiple times. Is this a java -> postgreSQL connector issue?

# Environment

Please provide as much information as possible about your environment:

- Hardware Make/Model: Digital Ocean droplet
- Operating System and Version (e.g. `cat /etc/os-release`): Ubuntu 22.10
- Docker Version (`docker -v`): 20.10.21
- Docker Compose Version (`docker compose version`) or (`docker-compose version`): 1.28.5
- CPU Details (make/model and/or speed/core count): Digital ocean hosting
- RAM (e.g. `free -h`): 2 Gib
- Disk Availability (e.g. `df -h`):  50 GB
- TAK Server Version From TAK.gov: takserver-docker-4.9-RELEASE-23.zip & takserver-docker-4.8-RELEASE-56.zip

# Description

# Steps to Reproduce

# Error output
![image](https://github.com/Cloud-RF/tak-server/assets/46629929/c1fe6249-0d12-4652-81a2-cc6acd454fcd)
No joy with DB at IP (it is the right one), will retry in 10s. If this loops more than 6 times go and get some fresh air...
java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.bbn.marti.takcl.cli.CommandCommon.invokeMethodFromModuleWithParams(CommandCommon.java:85)
        at com.bbn.marti.takcl.cli.advanced.AdvancedParamParser.execute(AdvancedParamParser.java:279)
        at com.bbn.marti.takcl.cli.advanced.AdvancedCliMainHelper.main(AdvancedCliMainHelper.java:127)
        at com.bbn.marti.UserManager.main(UserManager.java:58)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.bbn.marti.takcl.cli.CommandCommon.invokeMethodFromModuleWithParams(CommandCommon.java:52)
        ... 3 more
Caused by: class org.apache.ignite.IgniteException: Failed to find deployed service: distributed-user-file-manager
        at org.apache.ignite.internal.processors.service.GridServiceProxy.invokeMethod(GridServiceProxy.java:201)
        at org.apache.ignite.internal.processors.service.GridServiceProxy$ProxyInvocationHandler.invoke(GridServiceProxy.java:498)
        at com.sun.proxy.$Proxy43.getUsers(Unknown Source)
        at com.bbn.marti.takcl.AppModules.OnlineFileAuthModule.innerUserCertMod(OnlineFileAuthModule.java:137)
        at com.bbn.marti.takcl.AppModules.OnlineFileAuthModule.usermod(OnlineFileAuthModule.java:91)
        ... 8 more
java.lang.reflect.InvocationTargetException
ERROR: 1

**Comment by mikevb3** [comment]
Can confirm I'm having the same error using the 4.8 release 56, which is the latest at the moment of writing this.

Seems to be stuck on the process.

**Comment by FarrantAlex** [comment]
Try 4GB ram. The database has been put on a diet but the TS service requires a gross amount of memory.

**Comment by jeanburgos** [comment]
Friends, long story short my TAK server was working fine on Docker following these instructions. Then I attempted the video to generate intermediary certificates for ATAK and it broke it. I kept getting the whole "No Joy" thing.  Something about an authentication error. 

I after struggling for a few hours I decided to Nuke Postgres following [these steps](https://www.commandprompt.com/education/how-to-uninstall-postgresql-from-ubuntu/#:~:text=Conclusion-,To%20uninstall%20Postgres%20from%20your%20Ubuntu%20operating%20system%2C%20open%20the,%E2%80%9Csudo%20apt%20autoremove%E2%80%9D%20command.) then Nuked Docker completely (I know) following some of [these steps ](https://askubuntu.com/questions/935569/how-to-completely-uninstall-docker).

I gave Ubuntu an apt update and re-installed Docker before restarting this guide. 

Then like a charm it installed on the first try. Happy to announce all systems go. 
![installation fail](https://github.com/Cloud-RF/tak-server/assets/113867328/b3644166-1180-4574-874f-95d11e2e8e9a)

I hope this help, I guess not so short of a story.

**Comment by jdurago-rebellion** [comment]
I ran into the same issue and upgraded to `Docker 24.0.2` from Docker 20.10.21 and it worked

**Comment by FarrantAlex** [comment]
Thanks for the feedback. I suspect memory is optimised in the new Docker which explains why the failing process worked with the new version.
